version: '3.7'
services:
    postgres:
        image: postgres:10.5
        restart: always
        env_file:
          - .env
        ports:
          - '5438:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          - ../../00/00:/00 # change path to wherever it is downloaded
    pgadmin:
      container_name: pgadmin4_container
      image: dpage/pgadmin4
      restart: always
      env_file:
        - .env
      ports:
        - "5050:80"